version: '3.1'
services:
  db:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: vasya
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: mydb